menu:
    Blog: /
    Archive: /archives/
    GitHub: https://github.com/akuma
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: iakuma
duoshuo:

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2015
